version: 0.2

env:
  shell: bash
  parameter-store:
    DOCKERHUB_TOKEN:  DOCKERHUB_TOKEN
#    CODECOV_TOKEN: CODECOV_TOKEN
  exported-variables:
    - PROJECT_VERSION
    - IMAGE_EXISTS

phases:
  install:
    runtime-versions:
      docker: 18
      java: openjdk11
    commands:
      # Get information about this image, the current directory, maven version, docker version.
      # Update apg-get.
      # Install yq.
      - lsb_release -a
      - pwd
      - apt-get update
      - apt-get install -y maven
      - mvn --version
      - docker --version
      - java --version
      - docker info

  pre_build:
    commands:
      # Get project's version from pom.xml.
      - PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

      # Check if the image exists in docker hub already.  If the image tag matches the project's version from the POM,
      # then exit/fail the build.
      - IMAGE_EXISTS=$(docker pull joneschris/qb4j-api:"$PROJECT_VERSION" > /dev/null && echo "true" || echo "false")
      - echo "Does the image exist?  $IMAGE_EXISTS"
      - |
        if [ "$IMAGE_EXISTS" == "true" ]; then
          echo "The image, $PROJECT_VERSION, already exists.  You probably need to bump the project's version in the pom.xml."
          exit 1
        fi

      # Copy custom maven settings from S3 bucket.
      - aws s3 cp s3://maven-build-settings/qb4j_settings.xml /root/.m2/settings.xml

  build:
    commands:
      # Build the uber jar and run unit tests.
      - mvn clean install -Dmaven.javadoc.skip=true

      # Build docker image
      - docker image build -t joneschris/qb4j-api:"$PROJECT_VERSION" --build-arg project_version="$PROJECT_VERSION" .

  post_build:
    commands:
      # Zip the swarm directory.  Use the CODEBUILD_BUILD_NUMBER environment variable, which is the number of the build.
      - zip -r -j swarm_artifacts.zip ./cicd/deployment/swarm/
      # Copy the zip file to S3.
#      - aws s3 cp $ZIP_FILE s3://qb4j-mvc/$ZIP_FILE

      - bash ./cicd/buildspec_steps/1_post_build.bash "$DOCKERHUB_TOKEN" "$PROJECT_VERSION"

artifacts:
  files:
    - target/qb4j-api-$PROJECT_VERSION.jar
    - swarm_artifacts.zip
  discard-paths: yes
  secondary-artifacts:
    swarm_artifact:
      files:
        - swarm_artifacts.zip
#    code_coverage:
#      files:
#        - target/site/jacoco/**/*  # All files recursively in jacoco directory.
#      name: code_coverage.zip
cache:
  paths:
    - '/root/.m2/**/*'
