version: 0.2

env:
  shell: bash
  parameter-store:
    DOCKERHUB_TOKEN:  DOCKERHUB_TOKEN
#    CODECOV_TOKEN: CODECOV_TOKEN
  exported-variables:
    - PROJECT_VERSION
    - IMAGE_EXISTS

phases:
  install:
    runtime-versions:
      docker: 18
      java: openjdk8
    commands:
      - bash ./cicd/buildspec_steps/0_install.bash

  pre_build:
    commands:
      - bash ./cicd/buildspec_steps/1_pre_build.bash

  build:
    commands:
      - bash ./cicd/buildspec_steps/2_build.bash "$PROJECT_VERSION" "$ENV"

  post_build:
    commands:
      - bash ./cicd/buildspec_steps/3_post_build.bash "$DOCKERHUB_TOKEN" "$PROJECT_VERSION"

artifacts:
  files:
    - target/qb4j-api-$PROJECT_VERSION.jar
  discard-paths: yes
#  secondary-artifacts:
#    code_coverage:
#      files:
#        - target/site/jacoco/**/*  # All files recursively in jacoco directory.
#      name: code_coverage.zip
cache:
  paths:
    - '/root/.m2/**/*'
