version: '3.1'

services:

  hr_database:
    image: qb4j-mysql
    build:
      context: .
      dockerfile: database_dockerfiles/mysql.Dockerfile
    ports:
      - '3306:3306'

  finance_database:
    image: qb4j-postgresql
    build:
      context: .
      dockerfile: database_dockerfiles/postgresql.Dockerfile
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example

  database_metadata_cache:
    image: redis:latest
    ports:
      - '6379:6379'

