version: '3.1'

services:
  api:
    image: joneschris/qb4j-api:0.0.21
    ports:
    - '8080:8080'
    environment:
      - qb4j_config=${QB4J_CONFIG}  # QB4J_CONFIG should already be an exported variable in your shell in order to be interpolated here.
      - update_cache=true  # True if you want to test the cache refresh, otherwise false to run the image as the API.
    depends_on:
      - hr_database
      - database_metadata_cache
#      - finance_database
#    deploy:
#      restart_policy:
#        condition: on-failure
  hr_database:
    image: qb4j-mysql
    build:
      context: .
      dockerfile: mysql.Dockerfile
    ports:
      - '3306:3306'
##    deploy:
##      restart_policy:
##        condition: on-failure
#  finance_database:
#    image: qb4j-postgresql
#    build:
#      context: .
#      dockerfile: postgresql.Dockerfile
#    ports:
#      - '5432:5432'
##    deploy:
##      restart_policy:
##        condition: on-failure
  database_metadata_cache:
    image: redis:latest
    ports:
      - '6379:6379'

