targetDataSources:
  - name: finance_database
    url: jdbc:postgresql://database:5432/postgres
    driverClassName: org.postgresql.Driver
    databaseType: PostgreSQL
    username: postgres
    password: example
    excludeObjects:
      schemas: [
        information_schema,
        public,
        pg_catalog
      ]
      tables: []
      columns: []
databaseMetadataCacheSource:
  # An in-memory cache.
  cacheType: IN_MEMORY

  # A redis cache for local debugging.
  #  cacheType: REDIS
  #  host: localhost
  #  port: 6379

  # A redis cache without local debugging.
#  cacheType: REDIS
#  host: database_metadata_cache
#  port: 6379
queryTemplateDataSource:
  url: jdbc:sqlite:./data/query_templates.db
  driverClassName: org.sqlite.JDBC
