version: '3.8'

services:

  database:
#    image: postgres:13-alpine
    image: joneschris/qb4j-postgres:0.0.3
    ports:
      - '5432:5432'
#    volumes:
#      - ./database/finance_database:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example

  api:
    image: "joneschris/qb4j-api:${PROJECT_VERSION}"
    ports:
      - '8080:8080'  # Port the API runs on.
      - '5005:5005' # Debugging port.
    environment:
      - qb4j_config=${QB4J_CONFIG}  # QB4J_CONFIG should already be an exported variable in your shell in order to be interpolated here.
      - update_cache=${UPDATE_CACHE}  # True if you want to test the cache refresh, otherwise false to run the image as the API.
    depends_on:
      - database

