Parameters:
  ProjectName:
    Type: String
    Default: qb4j-ui
    Description:  The name of this project

Resources:
  CodeBuildDependencyCacheBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: dependencies-npm
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  CodeBuildArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: qb4j-ui
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: '2012-10-17'
      Policies:
        - PolicyDocument:
            Statement:
              - Action: ssm:GetParameters
                Effect: Allow
                Resource: "*"
              - Action: cloudformation:*
                Effect: Allow
                Resource: "*"
              - Action:
                  - ecs:*
                  - ec2:*
                  - iam:*
                  - logs:*
                  - elasticloadbalancing:*
                  - elasticloadbalancingv2:*
                  - route53:*
                  - s3:*
                Effect: Allow
                Resource: "*"
            Version: '2012-10-17'
          PolicyName: !Sub '${ProjectName}-CodeBuild'

  CodeBuildRoleDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject*
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - CodeBuildArtifactBucket
                  - Arn
              - Fn::Join:
                  - ''
                  - - Fn::GetAtt:
                        - CodeBuildArtifactBucket
                        - Arn
                    - "/*"
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject*
              - s3:Abort*
            Effect: Allow
            Resource: '*'
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ''
                  - - 'arn:'
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - ":log-group:/aws/codebuild/"
                    - Ref: CodeBuildProject
              - Fn::Join:
                  - ''
                  - - 'arn:'
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - ":log-group:/aws/codebuild/"
                    - Ref: CodeBuildProject
                    - ":*"
        Version: '2012-10-17'
      PolicyName: CodeBuildRoleDefaultPolicy
      Roles:
        - Ref: CodeBuildRole

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Location:
          Ref: CodeBuildArtifactBucket
        Name: qb4j-ui.zip
        NamespaceType: BUILD_ID
        Packaging: ZIP
        Path: build/
        Type: S3
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:1.0
        PrivilegedMode: false
        Type: LINUX_CONTAINER
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        GitCloneDepth: 1
        Location: https://github.com/jones-chris/qb-react-ui.git
        ReportBuildStatus: true
        Type: GITHUB
      BadgeEnabled: true
      Cache:
        Location:
          Fn::Join:
            - "/"
            - - Ref: CodeBuildDependencyCacheBucket
              - Ref: AWS::NoValue
        Type: S3
      Name: qb4j-ui
      SourceVersion: master
